version: '3'

services:

  runserver:
    build: .
    command: bash -c "python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  autotests:
    build: .
    command: bash -c "python /code/manage.py test"
    volumes:
      - .:/code
